workflows:
  ios-360-camera:
    name: 360 Camera iOS
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Build iOS unsigned
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app
      - /tmp/xcodebuild_logs/*.log
